// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nygsrorccqyegirwqmxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55Z3Nyb3JjY3F5ZWdpcndxbXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjY0NzcsImV4cCI6MjA2MTI0MjQ3N30.O5pmpdGnBx80xpLlSQI2iikXW6GrLfX5NCqu206QfWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);